name: solvent
description:
  A general purpose utilities package to write more readable, succinct Dart code.
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
