name: solvent
description:
  A package which enables you to write more readable, succinct Dart code by
  building on existing language features.
version: 0.1.1
repository: https://github.com/blaugold/solvent
homepage: https://github.com/blaugold/solvent

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.3
